[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy= """
        default-src 'self' *.swiftdoc.org;
        script-src 'self' 'unsafe-inline' https://www.google-analytics.com;
        style-src 'self' 'unsafe-inline';
        img-src 'self';
        frame-ancestors 'none';
        object-src 'none';
        connect-src 'self' https://www.google-analytics.com;
        base-uri 'none';
        upgrade-insecure-requests;
        report-uri https://readeval.report-uri.com/r/d/ct/reportOnly;
    """
    Expect-CT = """
        max-age=0, report-uri="https://readeval.report-uri.com/r/d/ct/reportOnly"
    """
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/feed.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

[[redirects]]
  from = "https://swiftdoc.netlify.com/*"
  to = "https://swiftdoc.org/:splat"

[[redirects]]
  from = "http://swiftdoc.netlify.com/*"
  to = "https://swiftdoc.org/:splat"
